IntexTwo/Components/CrashesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IntexTwo.Models;

namespace IntexTwo.Components
{
    public class CrashesViewComponent : ViewComponent
    {
        private CrashesDbContext _context { get; set; }

        public CrashesViewComponent(CrashesDbContext temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.Cities = RouteData?.Values["crashCity"];

            var cities = _context.Crashes
                .Select(crash => crash.CITY)
                .Distinct()
                .OrderBy(city => city);

            return View(cities);
        }
    }
}

IntexTwo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using IntexTwo.Models;
using IntexTwo.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace IntexTwo.Controllers
{
    public class HomeController : Controller
    {
        private CrashesDbContext _context { get; set; }

        public HomeController(CrashesDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Crashes(string cityName, int p = 1, int s = 25)
        {
            ViewBag.CityName = cityName ?? "Home";

            var crashes = _context.Crashes.ToList();
            var pageData = new CrashViewModel
            {
                Crashes = _context.Crashes
                            .Where(crash => crash.CITY == cityName || cityName == null)
                            .OrderBy(crash => crash.CRASH_ID)
                            .Skip((p - 1) * s)
                            .Take(s),

                PageInfo = new PageInformation
                {
                    NumOfCrashes = _context.Crashes.Count(),
                    CrashesPerPage = s,
                    CurrentPage = p
                }
            };
            return View(pageData);
        }

        public IActionResult CrashDetails(int crashId)
        {
            var crash = _context.Crashes.Single(x => x.CRASH_ID == crashId);

            return View(crash);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

IntexTwo/Views/Home/CrashDetails.cshtml
@{
    ViewData["Title"] = "Crash Details";
}

@model IntexTwo.Models.CrashModel

<div class="card border-light mb-4">
    <div class="card-content">
        <h3 class="card-header">Crash Details</h3>
        <div class="card-body cleartfix">
            <div class="media align-items-stretch">
                <div class="media-body">
                    <ul>
                        <li>ID: @Model.CRASH_ID</li>
                        <li>Date: @Model.CRASH_DATE</li>
                        <li>Time: @Model.CRASH_TIME</li>
                        <li>Route: @Model.ROUTE</li>
                        <li>Mile Point: @Model.MILEPOINT</li>
                        <li>Latitude: @Model.LAT_UTM_Y</li>
                        <li>Longitude: @Model.LONG_UTM_X</li>
                        <li>Name of Road: @Model.MAIN_ROAD_NAME</li>
                        <li>City: @Model.CITY</li>
                        <li>County: @Model.COUNTY_NAME</li>
                    </ul>
                </div>
                <div class="media-body">
                    <ul>
                        <li>&#128679 Work Zone Related: @Model.WORK_ZONE_RELATED</li>
                        <li>&#128694 Pedestrian Involved: @Model.PEDESTRIAN_INVOLVED</li>
                        <li>&#128692 Cyclist Involved: @Model.BICYCLIST_INVOLVED</li>
                        <li>&#127949 Motorcycle Involved: @Model.MOTORCYCLE_INVOLVED</li>
                        <li>&#9888 Improper Restraint: @Model.IMPROPER_RESTRAINT</li>
                        <li>&#128683 Unrestrained: @Model.UNRESTRAINED</li>
                        <li>&#127866 DUI: @Model.DUI</li>
                        <li>&#10133 Intersection Related: @Model.INTERSECTION_RELATED</li>
                        <li>&#128058 Wild Animal Related: @Model.WILD_ANIMAL_RELATED</li>
                        <li>&#128054 Domestic Animal Related: @Model.DOMESTIC_ANIMAL_RELATED</li>
                        <li>&#128260 Overturn Rollover: @Model.OVERTURN_ROLLOVER</li>
                        <li>&#128667 Commercial Vehicle Involved: @Model.COMMERCIAL_MOTOR_VEH_INVOLVED</li>
                        <li>&#128102 Teenage Driver Involved: @Model.TEENAGE_DRIVER_INVOLVED</li>
                        <li>&#128117 Older Driver Involved: @Model.OLDER_DRIVER_INVOLVED</li>
                        <li>&#127776 Night or Dark Condition: @Model.NIGHT_DARK_CONDITION</li>
                        <li>&#128663 Single Vehicle: @Model.SINGLE_VEHICLE</li>
                        <li>&#128064 Distracted Driving: @Model.DISTRACTED_DRIVING</li>
                        <li>&#128564 Drowsy Driving: @Model.DROWSY_DRIVING</li>
                        <li>&#128739 Roadway Departure: @Model.ROADWAY_DEPARTURE</li>
                    </ul>
                </div>
                <div class="align-self-center">
                    <h3>Crash Severity: @Model.CRASH_SEVERITY_ID</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<a class="btn btn-dark" role="button" asp-action="Crashes">Back</a>

IntexTwo/Views/Home/Crashes.cshtml
@{
    ViewData["Title"] = "Crashes";
}

@model CrashViewModel

<div class="card border-light mb-3">
    <div class="row m-1 p-1 justify-content-between align-items-center">
        <h1 class="row mt-3 ml-4">Crashes</h1>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:crashes></vc:crashes>
        </div>

        <div class="card-group col-9">
            @foreach (var crash in Model.Crashes)
            {
                <div class="col-xl-6 col-md-12 mb-4">
                    <div class="card card-stats mb-4 mb-xl-0">
                        <div class="card-body card-info">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-sm text-muted mb-0">@crash.CRASH_ID</h5>
                                    <span class="h3 font-weight-bold mb-0">@crash.CITY</span>
                                </div>
                                <div class="col-auto">
                                    <a class="btn btn-outline-info btn-sm" asp-controller="Home" asp-action="CrashDetails" asp-route-crashid="@crash.CRASH_ID">Details</a>
                                </div>
                            </div>
                            <p class="mt-0 mb-0 text-muted text-sm">
                                <span class="text-nowrap">@crash.CRASH_DATE @crash.CRASH_TIME</span>
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="row justify-content-center pt-5">
    <paging total-records="@Model.PageInfo.NumOfCrashes"
            page-no="@Model.PageInfo.CurrentPage"
            page-size="@Model.PageInfo.CrashesPerPage"
            show-page-size-nav="false"
            show-total-pages="false"
            show-total-records="false"></paging>
</div>

IntexTwo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="card border-light mb-3">
    <div class="py-1 my-2">
        <div class="col-lg-9 mx-auto">
            <h1 class="display-3 fw-bold mb-4">Utah Motor Vehicle Collision Report</h1>

            <p class="lead mb-4">
                This site reports on motor vehicle collisions occuring in Utah during three years: 2016, 2017, and 2019.
                It also includes potential solutions to help prevent more collisions in the future.
            </p>

            <h2 class="fw-bold mb-4 pt-2 text-muted">
                Utah has seen an increase in accidents caused by
                drinking and driving.
            </h2>

            <h3>Stats from the <span class="text-primary">Utah</span> Department of Health</h3>
            <ul class="lead mb-4">
                <li class="lead">A crash occurs in Utah every 8 minutes, a person is injured in a crash every 20 minutes, and a person dies in a crash every 33 hours.</li>
                <li class="lead">Motor vehicle crashes take a terrible toll on Utah families and communities and are a leading cause of injury-related death for Utahns.</li>
                <li class="lead">According to the Utah Highway Safety Office, in 2018 there were 62,074 motor vehicle crashes on public roadways in Utah, resulting in 25,645 injured persons and 260 deaths.</li>
            </ul>

            <img src="https://images.unsplash.com/photo-1543393716-375f47996a77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
                 style="width:100%"
                 class="mb-4" />

            <p class="lead mb-4">
                There are many factors such as age, gender, time, day, intoxication level etc. that can increase the liklihood of an individual getting into a crash in Utah.
                Understanding these factors that play a crucial role in a car crash can help predict potential future collisions in the Utah area and help us know how we can stop them.
            </p>

            <h3>Crash Severity By Month</h3>
            <iframe allow="geolocation"
                    src="https://opendata.utah.gov/dataset/Crash-Severity-by-Month/hgj5-q7bc/embed?width=800&height=600"
                    height="600" style="width: 100%; padding: 0; margin: 0; border: none;"></iframe>

            <h1 class="display-3 fw-bold mb-4"></h1>
            <h3>Top 7 Impacts of Crash Severity based on our Model</h3>
            <ul class="lead mb-4">
                <ol>1. Day & Time</ol>
                <ol>2. Month</ol>
                <ol>3. Motorcyle Involved</ol>
                <ol>4. Pedestrian Involved</ol>
                <ol>5. Car Rolls Over</ol>
                <ol>6. Bicyclist Involved</ol>
                <ol>7. Teenager Involved</ol>
            </ul>

            <h3>What You Can Do</h3>
            <ul class="lead mb-4">
                <li>Promote less driving in peak sleepiness periods (12:00am - 4:00am).</li>
                <li>Look for alternate routes or new road construction to make rush hour less busy.</li>
                <li>Promote safe driving on holidays. The summer months tend to have more severe crashes.</li>
                <li>Provide motorcyclists with education to best navigate streets and highways.</li>
                <li>Make sure crosswalks are safe and improve lighting in dimmed areas where crashes have occured.</li>
                <li>Keep promoting wearing seatbelts and slowing down for turns.</li>
                <li>Enforce and inform drivers of laws to require a safe distance to pass bycicles.</li>
                <li>Promote legislation to restrict young teen drivers from driving in risky conditions</li>
            </ul>

        </div>
    </div>
</div>