IntexTwo/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntexTwo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using IntexTwo.Models.ViewModels;

namespace IntexTwo.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private CrashesDbContext _context { get; set; }

        public AdminController(CrashesDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string cityName, int p = 1, int s = 25)
        {
            ViewBag.CityName = cityName ?? "Home";

            var crashes = _context.Crashes.ToList();
            var pageData = new CrashViewModel
            {
                Crashes = _context.Crashes
                            .Where(crash => crash.CITY == cityName || cityName == null) // filter
                            .OrderBy(crash => crash.CRASH_ID)
                            .Skip((p - 1) * s)
                            .Take(s),

                PageInfo = new PageInformation
                {
                    NumOfCrashes = _context.Crashes.Count(),
                    CrashesPerPage = s,
                    CurrentPage = p
                }
            };

            return View(pageData);
        }

        [HttpGet]
        public IActionResult CreateEditCrash()
        {
            return View();
        }

        [HttpPost] // Create new crash
        public IActionResult CreateEditCrash(CrashModel crash)
        {
            if (ModelState.IsValid)
            {
                crash.CRASH_ID = _context.Crashes.Count() + 1;
                _context.Add(crash);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(crash);
        }

        [HttpGet]
        public IActionResult Edit(int crashId)
        {
            ViewBag.Added = false;

            var crash = _context.Crashes.Single(crash => crash.CRASH_ID == crashId);

            return View("CreateEditCrash", crash);
        }

        [HttpPost] // Edit existing crash
        public IActionResult Edit(CrashModel crash)
        {
            if (ModelState.IsValid)
            {
                _context.Update(crash);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(crash);
        }

        [HttpGet]
        public IActionResult Delete(int crashId)
        {
            var crash = _context.Crashes.Single(x => x.CRASH_ID == crashId);

            return View(crash);
        }

        [HttpPost]
        public IActionResult Delete(CrashModel crash)
        {
            _context.Crashes.Remove(crash);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

IntexTwo/Controllers/InferenceController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using IntexTwo.Models;
using IntexTwo.Models.ViewModels;

namespace aspnetcore.Controllers
{
    public class InferenceController : Controller
    {
        private InferenceSession _session;

        public InferenceController(InferenceSession session)
        {
            _session = session;
        }
        [HttpGet]
        public IActionResult Calculator ()
        {
            return View();
        }


        [HttpPost]
       public IActionResult Result (CrashSeverityData data)
        {
            var result = _session.Run(new List<NamedOnnxValue>
            {
                NamedOnnxValue.CreateFromTensor("float_input", data.AsTensor())
            });
            Tensor<float> score = result.First().AsTensor<float>();
            var prediction = new Prediction { PredictedValue = score.First()};
            result.Dispose();
            /*ViewBag.Result = prediction.PredictedValue;*/
            return View(prediction);
        }
    }
}

IntexTwo/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UMVCR @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="http://example.com/favicon.png">
</head>
<body background="https://images.unsplash.com/photo-1616445403956-c66a6b11e3f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow pt-3 pb-3 mb-3">
            <div class="container">
                <a class="navbar-brand text-light " asp-area="" asp-controller="Home" asp-action="Index">UMVCR</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Crashes">Crashes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Inference" asp-action="Calculator">Calculator</a>
                            </li>

                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="">Admin</a>
                                </li>
                            }
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container text-light">
                &copy; 2022 - IntexTwo - <a class= "text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>