IntexTwo/Components/FilterViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IntexTwo.Models;

namespace IntexTwo.Components
{
    public class FilterViewComponent : ViewComponent
    {
        private CrashesDbContext _context { get; set; }

        public FilterViewComponent(CrashesDbContext temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.Cities = RouteData?.Values["crashCity"];

            var cities = _context.Crashes
                .Select(crash => crash.CITY)
                .Distinct()
                .OrderBy(city => city);

            return View(cities);
        }
    }
}

IntexTwo/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntexTwo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using IntexTwo.Models.ViewModels;

namespace IntexTwo.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private CrashesDbContext _context { get; set; }

        public AdminController(CrashesDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string cityName, int p = 1, int s = 25)
        {
            ViewBag.CityName = cityName ?? "Home";

            var crashes = _context.Crashes.ToList();
            var pageData = new CrashViewModel
            {
                Crashes = _context.Crashes
                            .Where(crash => crash.CITY == cityName || cityName == null) // filter
                            .OrderBy(crash => crash.CRASH_ID)
                            .Skip((p - 1) * s)
                            .Take(s),

                PageInfo = new PageInformation
                {
                    NumOfCrashes = _context.Crashes.Count(),
                    CrashesPerPage = s,
                    CurrentPage = p
                }
            };

            return View(pageData);
        }

        [HttpGet]
        public IActionResult CreateEditCrash()
        {
            return View();
        }

        [HttpPost] // Create new crash
        public IActionResult CreateEditCrash(CrashModel crash)
        {
            if (ModelState.IsValid)
            {
                crash.CRASH_ID = _context.Crashes.Count() + 1;
                _context.Add(crash);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(crash);
        }

        [HttpGet]
        public IActionResult Edit(int crashId)
        {
            ViewBag.Added = false;

            var crash = _context.Crashes.Single(crash => crash.CRASH_ID == crashId);

            return View("CreateEditCrash", crash);
        }

        [HttpPost] // Edit existing crash
        public IActionResult Edit(CrashModel crash)
        {
            if (ModelState.IsValid)
            {
                _context.Update(crash);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(crash);
        }

        [HttpGet]
        public IActionResult Delete(int crashId)
        {
            var crash = _context.Crashes.Single(x => x.CRASH_ID == crashId);

            return View(crash);
        }

        [HttpPost]
        public IActionResult Delete(CrashModel crash)
        {
            _context.Crashes.Remove(crash);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

IntexTwo/Views/Admin/CreateEditCrash.cshtml
@{
    ViewData["Title"] = "Create/Edit Crash";
}

@model IntexTwo.Models.CrashModel

<div class="card border-light mb-4">
    <div class="row m-1 p-1 justify-content-between align-items-center">
        <h1 class="row mt-3 ml-4">Create/Edit Crash</h1>
    </div>

    <form method="post" class="mb-4">
        <div asp-validation-summary="All"></div>

        <div class="form-group mx-5">
            <label asp-for="CRASH_DATE">Date</label>
            <input type="text" class="form-control" asp-for="CRASH_DATE">
        </div>

        <div class="form-group mx-5">
            <label asp-for="CRASH_TIME">Time</label>
            <input type="text" class="form-control" asp-for="CRASH_TIME">
        </div>

        <div class="form-group mx-5">
            <label asp-for="ROUTE">Route</label>
            <input type="number" class="form-control" asp-for="ROUTE">
        </div>

        <div class="form-group mx-5">
            <label asp-for="MILEPOINT">Mile Point</label>
            <input step="any" type="number" class="form-control" asp-for="MILEPOINT">
        </div>

        <div class="form-group mx-5">
            <label asp-for="LAT_UTM_Y">Latitude</label>
            <input step="any" type="number" class="form-control" asp-for="LAT_UTM_Y">
        </div>

        <div class="form-group mx-5">
            <label asp-for="LONG_UTM_X">Longitude</label>
            <input step="any" type="number" class="form-control" asp-for="LONG_UTM_X">
        </div>

        <div class="form-group mx-5">
            <label asp-for="MAIN_ROAD_NAME">Road Name</label>
            <input type="text" class="form-control" asp-for="MAIN_ROAD_NAME" style="text-transform:uppercase">
        </div>

        <div class="form-group mx-5">
            <label asp-for="CITY">City</label>
            <input type="text" class="form-control" asp-for="CITY" style="text-transform:uppercase">
        </div>

        <div class="form-group mx-5">
            <label asp-for="COUNTY_NAME">County</label>
            <input type="text" class="form-control" asp-for="COUNTY_NAME" style="text-transform:uppercase">
        </div>

        <div class="form-group mx-5">
            <label asp-for="CRASH_SEVERITY_ID">Severity</label>
            <input step="any" type="number" class="form-control" asp-for="CRASH_SEVERITY_ID">
        </div>

        <div class="row m-1 p-1">
            <div class="col-3">
                <div class="form-group ml-5">
                    <label asp-for="WORK_ZONE_RELATED">Work Zone Related</label>
                    <input type="checkbox" class="form-control" asp-for="WORK_ZONE_RELATED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="PEDESTRIAN_INVOLVED">Pedestrian Involved</label>
                    <input type="checkbox" class="form-control" asp-for="PEDESTRIAN_INVOLVED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="BICYCLIST_INVOLVED">Bycyclist Involved</label>
                    <input type="checkbox" class="form-control" asp-for="BICYCLIST_INVOLVED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="MOTORCYCLE_INVOLVED">Motorcycle Involved</label>
                    <input type="checkbox" class="form-control" asp-for="MOTORCYCLE_INVOLVED" />
                </div>

                <div class="form-group ml-5">
                    <label asp-for="DISTRACTED_DRIVING">Distracted Driving</label>
                    <input type="checkbox" class="form-control" asp-for="DISTRACTED_DRIVING">
                </div>
            </div>

            <div class="col-3">
                <div class="form-group ml-5">
                    <label asp-for="IMPROPER_RESTRAINT">Improper Restraint</label>
                    <input type="checkbox" class="form-control" asp-for="IMPROPER_RESTRAINT">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="UNRESTRAINED">Unrestrained</label>
                    <input type="checkbox" class="form-control" asp-for="UNRESTRAINED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="DUI">DUI</label>
                    <input type="checkbox" class="form-control" asp-for="DUI">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="INTERSECTION_RELATED">Intersection Related</label>
                    <input type="checkbox" class="form-control" asp-for="INTERSECTION_RELATED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="DROWSY_DRIVING">Drowsey Driving</label>
                    <input type="checkbox" class="form-control" asp-for="DROWSY_DRIVING">
                </div>
            </div>

            <div class="col-3">
                <div class="form-group ml-5">
                    <label asp-for="WILD_ANIMAL_RELATED">Wild Animal Related</label>
                    <input type="checkbox" class="form-control" asp-for="WILD_ANIMAL_RELATED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="DOMESTIC_ANIMAL_RELATED">Domestic Animal Related</label>
                    <input type="checkbox" class="form-control" asp-for="DOMESTIC_ANIMAL_RELATED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="OVERTURN_ROLLOVER">Overturn Rollover</label>
                    <input type="checkbox" class="form-control" asp-for="OVERTURN_ROLLOVER">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="COMMERCIAL_MOTOR_VEH_INVOLVED">CMV Involved</label>
                    <input type="checkbox" class="form-control" asp-for="COMMERCIAL_MOTOR_VEH_INVOLVED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="ROADWAY_DEPARTURE">Roadway Departure</label>
                    <input type="checkbox" class="form-control" asp-for="ROADWAY_DEPARTURE" value="ROAD">
                </div>
            </div>

            <div class="col-3">
                <div class="form-group ml-5">
                    <label asp-for="TEENAGE_DRIVER_INVOLVED">Teenage Driver Involved</label>
                    <input type="checkbox" class="form-control" asp-for="TEENAGE_DRIVER_INVOLVED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="OLDER_DRIVER_INVOLVED">Older Driver Involved</label>
                    <input type="checkbox" class="form-control" asp-for="OLDER_DRIVER_INVOLVED">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="NIGHT_DARK_CONDITION">Night Dark Condition</label>
                    <input type="checkbox" class="form-control" asp-for="NIGHT_DARK_CONDITION">
                </div>

                <div class="form-group ml-5">
                    <label asp-for="SINGLE_VEHICLE">Single Vehicle</label>
                    <input type="checkbox" class="form-control" asp-for="SINGLE_VEHICLE">
                </div>
            </div>
        </div>

        @if (ViewBag.Added == false)
        {
            <input type="hidden" asp-for="CRASH_ID" />
        }

        <a class="btn btn-outline-secondary ml-5 mt-3" role="button" asp-action="Index">Cancel</a>
        <button type="submit" class="btn btn-outline-success mt-3">Submit</button>
    </form>
</div>

IntexTwo/Views/Admin/Delete.cshtml
@{
    ViewData["Title"] = "Delete Crash";
}

@model CrashModel

<h1 class="text-danger">Are you sure you want to YEET the record for crash @Model.CRASH_ID?</h1>

<form method="post" asp-controller="Admin" asp-action="Delete">
    <a class="btn btn-info btn-sm" role="button" asp-controller="Admin" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-danger btn-sm">Delete</button>

    <input type="hidden" asp-for="CRASH_ID" />
</form>

IntexTwo/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin";
}

@model CrashViewModel

<div class="card border-light mb-3">
    <div class="row m-1 p-1 justify-content-between align-items-center">
        <h1 class="row mt-3 ml-4">Admin</h1>

        <a class="btn btn-outline-success pb-2" role="button" asp-action="CreateEditCrash">Add Record</a>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:filter></vc:filter>
        </div>

        <table class="table col-9">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                    <th scope="col">City</th>
                    <th scope="col">Road</th>
                    <th scope="col">Severity</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var crash in Model.Crashes)
                {
                    <tr>
                        <th scope="row">@crash.CRASH_ID</th>
                        <td>@crash.CRASH_DATE</td>
                        <td>@crash.CRASH_TIME</td>
                        <td>@crash.CITY</td>
                        <td>@crash.MAIN_ROAD_NAME</td>
                        <td>@crash.CRASH_SEVERITY_ID</td>
                        <td><a class="btn btn-outline-info btn-sm" role="button" asp-action="Edit" asp-route-crashId="@crash.CRASH_ID">Edit</a></td>
                        <td><a class="btn btn-outline-danger btn-sm" role="button" asp-action="Delete" asp-route-crashId="@crash.CRASH_ID">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="row justify-content-center pt-5">
    <paging total-records="@Model.PageInfo.NumOfCrashes"
            page-no="@Model.PageInfo.CurrentPage"
            page-size="@Model.PageInfo.CrashesPerPage"
            show-page-size-nav="false"
            show-total-pages="false"
            show-total-records="false"></paging>
</div>